version: '2.5'

networks:
  cc_network:

services:
  db: 
    image: mariadb:10.6
    container_name: cc_database
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    networks:
      - cc_network
    volumes:
      - ./cc_database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    cpus: "0.5"
    mem_limit: 300M

  app:
    image: nextcloud
    container_name: cc_nextcloud
    restart: always
    ports:
      - 8080:80
    networks:
      - cc_network
    volumes:
      - ./cc_nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    cpus: "2"
    mem_limit: 1200M
    depends_on:
      - db
    
  locust:
    image: locustio/locust
    container_name: cc_locust
    ports:
      - 8888:80
    volumes:
      - ./locust:/locust
    command: -f /locust/locustfile.py --host=http://cc_nextcloud
    environment:
      - LOCUST_WEB_PORT=80
    networks:
      - cc_network
    cpus: "1"
    mem_limit: 600M
    depends_on:
      - app